apiVersion: v1
kind: ConfigMap
metadata:
  name: authn-authz
  namespace: system
data:
  master-config: |
    kind: ClusterConfiguration
    apiVersion: kubeadm.k8s.io/v1beta1
    apiServer:
      extraArgs:
        authentication-mode: Webhook
        authentication-token-webhook-config-file: "/etc/weaveworks/wks/authn-config.yaml"
        authentication-token-webhook-cache-ttl: 24h
        authorization-mode: Webhook
        authorization-webhook-config-file: "/etc/weaveworks/wks/authz-config.yaml"
        authorization-webhook-cache-unauthorized-ttl: 1h
        authorization-webhook-cache-authorized-ttl: 24h
  authn-config: |
    # Kubernetes API version
    apiVersion: v1
    # kind of the API object
    kind: Config
    # clusters refers to the remote service.
    clusters:
      - name: name-of-remote-authn-service
        cluster:
          certificate-authority: "/etc/weaveworks/wks/pem/authn-ca.pem"   # CA for verifying the remote service.
          server: https://host.docker.internal/authenticate # URL of remote service to query. Must use 'https'.

    # users refers to the API server's webhook configuration.
    users:
      - name: name-of-api-server
        user:
          client-certificate: "/etc/weaveworks/wks/pem/authn-cert.pem" # cert for the webhook plugin to use
          client-key: "/etc/weaveworks/wks/pem/authn-key.pem"          # key matching the cert

    # kubeconfig files require a context. Provide one for the API server.
    current-context: webhook
    contexts:
      - context:
          cluster: name-of-remote-authn-service
          user: name-of-api-sever
        name: webhook
  authz-config: |
    # Kubernetes API version
    apiVersion: v1
    # kind of the API object
    kind: Config
    # clusters refers to the remote service.
    clusters:
      - name: name-of-remote-authz-service
        cluster:
          certificate-authority: "/etc/weaveworks/wks/pem/authz-ca.pem"   # CA for verifying the remote service.
          server: https://host.docker.internal/authorize # URL of remote service to query. Must use 'https'.

    # users refers to the API server's webhook configuration.
    users:
      - name: name-of-api-server
        user:
          client-certificate: "/etc/weaveworks/wks/pem/authz-cert.pem" # cert for the webhook plugin to use
          client-key: "/etc/weaveworks/wks/pem/authz-key.pem"          # key matching the cert

    # kubeconfig files require a context. Provide one for the API server.
    current-context: webhook
    contexts:
      - context:
          cluster: name-of-remote-authz-service
          user: name-of-api-sever
        name: webhook
