apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  clusterNetwork:
    services:
      cidrBlocks: [10.96.0.0/12]
    pods:
      cidrBlocks: [192.168.0.0/16]
    serviceDomain: cluster.local
  providerSpec:
    value:
      apiVersion: baremetalproviderspec/v1alpha1
      kind: BareMetalClusterProviderSpec
      sshKeyPath: /Users/jerry/src/github.com/weaveworks/wks/examples/footloose/cluster-key
      user: root
      authenticationWebhook:
        cacheTTL: 24h
        secret: authn
        url: https://host.docker.internal:5001/authenticate
      authorizationWebhook:
        unauthorizedTTL: 1h
        authorizedTTL: 24h
        secret: authz
        url: https://host.docker.internal:5001/authorize
      os:
        files:
        - source:
            configmap: repo
            key: kubernetes.repo
          destination: /etc/yum.repos.d/kubernetes.repo
        - source:
            configmap: repo
            key: docker-ce.repo
          destination: /etc/yum.repos.d/docker-ce.repo
      cri:
        kind: docker
        package: docker-ce
        version: 18.06.2.ce
      addons:
      - name: ingress-nginx
        deps: [https://raw.githubusercontent.com/kubernetes/ingress-nginx/1f4469fc217cddfde5abef7fbeeac9eeda520434/deploy/mandatory.yaml]
        params:
          type: "NodePort"
          httpPort: "30080"
          httpsPort: "30443"
