apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  clusterNetwork:
    services:
      cidrBlocks: [10.96.0.0/12]
    pods:
      cidrBlocks: [192.168.0.0/16]
    serviceDomain: cluster.local
  providerSpec:
    value:
      apiVersion: baremetalproviderspec/v1alpha1
      kind: BareMetalClusterProviderSpec
      sshKeyPath: /Users/jerry/src/github.com/weaveworks/wks/examples/footloose/cluster-key
      user: root
      os:
        files:
        - source:
            configmap: repo
            key: kubernetes.repo
          destination: /etc/yum.repos.d/kubernetes.repo
        - source:
            configmap: repo
            key: docker-ce.repo
          destination: /etc/yum.repos.d/docker-ce.repo
        - source:
            configmap: authn-authz
            key: master-config
          destination: /etc/weaveworks/wks/master-config.yaml
        - source:
            configmap: authn-authz
            key: authn-config
          destination: /etc/weaveworks/wks/authn-config.yaml
        - source:
            configmap: authn-authz
            key: authz-config
          destination: /etc/weaveworks/wks/authz-config.yaml
      cri:
        kind: docker
        package: docker-ce
        version: 18.06.2.ce
      addons:
      - name: ingress-nginx
        deps: ["https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml"]
        params:
          type: "NodePort"
          httpPort: "30080"
          httpsPort: "30443"
