apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  name: t100
  labels:
    set: node
    mylabel: fooglor
spec:
  providerSpec:
    value:
      apiVersion: baremetalproviderspec/v1alpha1
      kind: BareMetalMachineProviderSpec
      public:
        address: 127.0.0.1
        port: 2223
      private:
        address: 172.17.0.5
        port: 22
  versions:
    kubelet: 1.13.5
